### ISSUE TITLE
Swiping on Child Items doesn't swipe

### ISSUE THREAD

**Issue by sharukhmohammed** [guochong/VerticalViewPager#1]
Whenever I try to swipe on child views like TextViews, the swipe isn't working. It only works when swiped in an empty space.

**Comment by chadguo** [comment]
As the readme said:
Works well with RecyclerView and ListView, currently not support TextView or ImageView as child directly, but you can put everything into RecyclerView and ListView.
————————————
please wrap your textViews with recyclerview or listview

**Comment by chadguo** [comment]
@sharukhmohammed
As the readme said:
Works well with RecyclerView and ListView, currently not support TextView or ImageView as child directly, but you can put everything into RecyclerView and ListView.
————————————
please wrap your textViews with recyclerview or listview

**Comment by sharukhmohammed** [comment]
I have switched to implementing the **same functionality** in a _RecyclerView and SnapHelper (Paged)_ so, can't test it out. Thanks.
